
(function(){
'use strict';
var project=window.SCHEDULE_PROJECT||{},trs=window.SCHEDULE_TRS||[],activities=window.SCHEDULE_ACTIVITIES||[],images=window.TR_IMAGES||{};
function $(q){return document.querySelector(q)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function num(p){return parseFloat(String(p||'0').replace('%','').replace(',','.'))||0}
function status(p){var n=num(p);return n>=100?'done':n>0?'progress':'pending'}
function statusText(p){var s=status(p);return s==='done'?'Concluída':s==='progress'?'Em andamento':'Não iniciada'}
function statsFor(tr){var sum=trs.find(function(x){return x.tr===tr}),list=activities.filter(function(x){return x.tr===tr}),done=list.filter(function(x){return num(x.progress)>=100}).length;return{summary:sum,list:list,done:done}}
function renderSummary(){var completed=activities.filter(function(x){return num(x.progress)>=100}).length;$('#summaryCards').innerHTML=
'<div class="card"><span>Avanço geral</span><strong>'+esc(project.progress)+'</strong><small>Previsto: '+esc(project.planned)+'</small></div>'+
'<div class="card"><span>Transportadores</span><strong>'+trs.length+'</strong><small>TR-2036KS-09 a 20</small></div>'+
'<div class="card"><span>Atividades concluídas</span><strong>'+completed+'/'+activities.length+'</strong><small>100% executadas na revisão</small></div>'+
'<div class="card"><span>Término previsto</span><strong>'+esc(project.end||'—')+'</strong><small>Marco contratual: '+esc(project.contractDeadline||'—')+'</small></div>';
var n=$('#scheduleNotice');n.className='notice ok';n.textContent='Término previsto no cronograma: '+(project.end||'—')+'. Marco contratual informado: '+(project.contractDeadline||'—')+'.'}
function tileHtml(item){var p=num(item.summary.progress),s=status(item.summary.progress),label=s==='done'?'Concluída':s==='progress'?'Em andamento':'Programada',tileState=s==='progress'?'working':s;return '<article class="tr-tile tile-'+tileState+'" tabindex="0" role="button" data-tr="'+item.tr+'" aria-label="Abrir cronograma da TR-'+item.tr+'"><div class="tile-top"><span>TRANSPORTADOR</span><span class="tile-arrow">↗</span></div><h3>TR-'+item.tr+'</h3><div class="tile-state"><b class="tile-'+s+'-label">'+label+'</b></div><div class="tile-progress"><div class="progress"><i style="width:'+Math.max(0,Math.min(100,p))+'%"></i></div><strong>'+esc(item.summary.progress)+'</strong></div><div class="tile-foot"><span>'+item.done+'/'+item.list.length+' atividades concluídas</span><span>Fim '+esc(item.summary.end)+'</span></div></article>'}
function renderTiles(){var tf=$('#trFilter').value,sf=$('#statusFilter').value,list=trs.map(function(s){var x=statsFor(s.tr);return{tr:s.tr,summary:s,list:x.list,done:x.done}}).filter(function(x){return(tf==='all'||x.tr===tf)&&(sf==='all'||sf===status(x.summary.progress))});$('#trGrid').innerHTML=list.map(tileHtml).join('')||'<div class="empty-state">Nenhuma TR atende a este filtro.</div>';$('#trGrid').querySelectorAll('[data-tr]').forEach(function(card){card.onclick=function(){openTR(card.dataset.tr)};card.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();openTR(card.dataset.tr)}}})}
function openTR(tr){var info=statsFor(tr),s=info.summary,list=info.list.sort(function(a,b){return a.id-b.id});$('#trTitle').textContent='TR-'+tr;$('#trSubtitle').textContent='Avanço da TR: '+s.progress+' · '+info.done+' de '+list.length+' atividades concluídas';var image=images[tr],photo=image?'<figure class="tr-photo"><img src="'+esc(image)+'" alt="Foto de campo da TR-'+tr+'" onerror="this.parentNode.remove()"><figcaption>Registro de campo · TR-'+tr+'</figcaption></figure>':'<div class="photo-empty"><span>REGISTRO DE CAMPO</span><strong>TR-'+tr+'</strong><small>Sem imagem nesta revisão</small></div>';var rows=list.map(function(x,i){var st=status(x.progress);return '<article class="activity-card '+(st==='done'?'is-done':st==='progress'?'is-progress':'is-pending')+'"><div class="sequence-no">'+String(i+1).padStart(2,'0')+'<i></i></div><div class="activity-body"><div class="activity-top"><span class="activity-dates">Início '+esc(x.start)+' · Término '+esc(x.end)+'</span><span class="status '+st+'">'+statusText(x.progress)+'</span></div><h3>'+esc(x.fullName)+'</h3><div class="activity-meta"><span><b>Duração</b> '+esc(x.duration)+'</span><span><b>Previsto</b> '+esc(x.planned)+'</span><span><b>Concluído</b> '+esc(x.progress)+'</span></div><div class="activity-bottom"><div class="progress"><i style="width:'+Math.max(0,Math.min(100,num(x.progress)))+'%"></i></div><span>'+esc(x.progress)+' executado</span></div></div></article>'}).join('');$('#trDetail').innerHTML='<div class="tr-detail-layout">'+photo+'<div class="tr-metrics"><div><span>Avanço da TR</span><strong>'+esc(s.progress)+'</strong><small>Previsto: '+esc(s.planned)+'</small></div><div><span>Atividades concluídas</span><strong>'+info.done+'/'+list.length+'</strong><small>Conforme revisão 03</small></div><div><span>Início da TR</span><strong class="date-exact">'+esc(s.start)+'</strong><small>Duração: '+esc(s.duration)+'</small></div><div><span>Entrega prevista</span><strong class="date-exact">'+esc(s.end)+'</strong><small>Data/hora do cronograma</small></div></div></div><div class="sequence-heading"><div><h3>Atividades na ordem do cronograma</h3><span>Nomes e datas transcritos da revisão 03.</span></div></div><div class="activity-list">'+rows+'</div>';$('#trModal').classList.add('show');$('#trModal').setAttribute('aria-hidden','false')}
function closeTR(){$('#trModal').classList.remove('show');$('#trModal').setAttribute('aria-hidden','true')}
$('#trClose').onclick=closeTR;$('#trModal').onclick=function(e){if(e.target.id==='trModal')closeTR()};document.addEventListener('keydown',function(e){if(e.key==='Escape')closeTR()});$('#trFilter').onchange=renderTiles;$('#statusFilter').onchange=renderTiles;
trs.forEach(function(x){var o=document.createElement('option');o.value=x.tr;o.textContent='TR-'+x.tr;$('#trFilter').appendChild(o)});
renderSummary();renderTiles();
})();
